spring.application.name=security
server.port = 8081

data.username = root
data.password = Sagar@1998

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#spring.security.user.name=Sagar
#spring.security.user.password=Sagar@1998
spring.main.allow-circular-references=true